version: '3.8'
services:
  postgres-local:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  arango-local:
    image: arangodb:3.9.2
    environment:
      - ARANGO_ROOT_PASSWORD=frinx
    ports:
      - 8529:8529
