name: Hive Check

on:
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.X-stable'

    tags:
      - 'v*'
      - 'v[0-9]+.[0-9]+.[0-9]-stable'

jobs:
  hive-check:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Stable token
        if: github.ref_type == 'branch' && endsWith(github.base_ref, '-stable')
        run: |
          echo "HIVE_TOKEN=${{ secrets.HIVE_STABLE_LATEST_TOKEN }}" >> "$GITHUB_ENV"

      - name: Master token
        if: github.ref_type == 'branch' && github.base_ref == 'main'
        run: |
          echo "HIVE_TOKEN=${{ secrets.HIVE_MASTER_LATEST_TOKEN }}" >> "$GITHUB_ENV"

      - name: Stable release token
        if: github.ref_type == 'tag' && endsWith(github.ref, '-stable')
        run: |
          echo "HIVE_TOKEN=${{ secrets.HIVE_STABLE_RELEASE_TOKEN }}" >> "$GITHUB_ENV"

      - name: Master release token
        if: ${{ github.ref_type == 'tag' && !endsWith(github.ref, '-stable') }}
        run: |
          echo "HIVE_TOKEN=${ secrets.HIVE_MASTER_RELEASE_TOKEN }" >> "$GITHUB_ENV"

      - name: schema check
        env:
          SCHEMA_PATH: 'src/schema/api.graphql'
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
          hive schema:check ${{ env.SCHEMA_PATH }} \
            --registry.accessToken ${HIVE_TOKEN} \
            --github
