name: PR check

on:
  pull_request:
    branches:
      - master

jobs:
  formatter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: node:fermium-alpine
          options: -v ${{ github.workspace }}:/work
          run: |
            cd /work && \
            apk update && \
            apk add --virtual build-essential build-base gcc wget git && \
            cp yarn.lock yarn.lock.orig && \
            yarn install && \
            cmp yarn.lock yarn.lock.orig && \
            yarn run prisma:generate && \
            yarn run formatter:check && \
            yarn run lint && \
            yarn run type-check
