name: PR check
on:
  pull_request:
    branches:
      - master
jobs:
  pr-check:
    runs-on: ubuntu-latest
    container: node:14-alpine
    services:
      postgres:
        image: postgres:12-alpine
        env:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Copy yarn.lock file
        run: cp yarn.lock yarn.lock.orig
      - name: Install dependencies
        run: yarn install --immutable
      - name: Generate prisma client
        run: yarn run prisma:generate
      - name: Test the code
        run: yarn run test
        env:
          - DATABASE_URL: postgresql://postgres:postgres@postgres:5432/frinx
      - name: Check code formatting
        run: yarn run formatter:check
      - name: Run eslint check
        run: yarn run lint
      - name: Run TS typecheck
        run: yarn run type-check
